title:              "Hands-on Korea"
tagline:            "Marketing, Trends, and Culture Stories in S.Korea"
email:              "yoochan.sohn@gmail.com"
description:        "영어공부 하는 한국인과 외국인들을 위한 대한민국의 마케팅, 트렌드, 문화 이야기 in English"
author:             "Yoo-Chan 'Gamgee' Sohn"
baseurl:            "/"
url:                "https://hoticehands.github.io"
locale:             "ko_KR"
thumbnail:          "/img/blogthumbnail.jpg"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

  # 블로그 disqus shortname
disqus:
  shortname: hoticehands-github-io
